name: "Platform CD - Terraform, Docker, and Kubernetes Actions"

on:
  schedule:
    # Run from Monday to Friday at 6:00 AM
    - cron: "0 6 * * 1-5"
  workflow_dispatch:
    inputs:
      action:
        description: "Select the action to perform"
        default: "terraform"
        type: choice
        options:
          - terraform
          - docker
          - kubernetes
      terraform_option:
        description: "Terraform option"
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy
      docker_option:
        description: "Docker option"
        default: "build"
        type: choice
        options:
          - build
          - push
      environment:
        description: "Environment to deploy applications to"
        default: "qa"
        type: choice
        options:
          - dev
          - qa

permissions: 
  id-token: write
  contents: read

env:
  CLUSTER_NAME: "aks-lgtm-${{ github.event.inputs.environment }}"
  RESOURCE_GROUP: "${{ vars.RESOURCE_GROUP }}"

jobs:
  terraform-execute:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'terraform' }}
    env:
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.AZURE_MI_CLIENT_ID }}
      TF_VERSION: 1.7.4
      RESOURCE_GROUP: ${{ vars.TF_RESOURCE_GROUP }}
      STORAGE_ACCOUNT: ${{ vars.TF_STORAGE_ACCOUNT }}
      STORAGE_SECRET: ${{ secrets.TF_STORAGE_SECRET }}
      CONTAINER_NAME: ${{ vars.TF_CONTAINER_NAME }}
      STATE_KEY: ${{ vars.TF_STATE_KEY }}
      GIT_TOKEN: ${{ secrets.GH_TOKEN }}
      GITRUNNER_TOKEN: ${{ secrets.RUNNER_REGISTRATION_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: 'Authenticate to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
  
      - name: Terraform init
        run: terraform init -backend-config="resource_group_name=${{ env.RESOURCE_GROUP }}" -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT }}" -backend-config="container_name=${{env.CONTAINER_NAME}}" -backend-config="key=${{env.STATE_KEY}}" -backend-config="access_key=${{env.STORAGE_SECRET}}"

      - name: Terraform ${{ github.event.inputs.terraform_option }}
        run: terraform ${{ github.event.inputs.terraform_option }} --var-file=${{ github.event.inputs.environment }}.tfvars -var="runner_token=${{env.GITRUNNER_TOKEN}}" -auto-approve -input=false

  docker-actions:
    name: Docker Actions
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'docker' }}
    environment: "${{ github.event.inputs.environment }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to ACR
        if: ${{ github.event.inputs.docker_option == 'push' }}
        uses: azure/docker-login@v1
        with:
          login-server: ${{ needs.terraform-execute.outputs.ACR_REPO }}
          username: ${{ needs.terraform-execute.outputs.ACR_USER }}
          password: ${{ needs.terraform-execute.outputs.ACR_PASS }}

      - name: Build Docker image
        if: ${{ github.event.inputs.docker_option == 'build' }}
        run: |
          docker build -t ${{ needs.terraform-execute.outputs.ACR_REPO }}/my-app:${{ github.sha }} .

      - name: Push Docker image
        if: ${{ github.event.inputs.docker_option == 'push' }}
        run: |
          docker push ${{ needs.terraform-execute.outputs.ACR_REPO }}/my-app:${{ github.sha }}

  kubernetes-deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'kubernetes' }}
    environment: "${{ github.event.inputs.environment }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate to Azure AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/my-app my-app=${{ needs.terraform-execute.outputs.ACR_REPO }}/my-app:${{ github.sha }}
